// src/lib/permit-pdf.js
// Generates Durham permit application PDFs that mirror the official Doc.983 Rev.08.01.2025 layout
// Fields, section order, Yes/No checkboxes, and footer match the official Durham form exactly

import { jsPDF } from 'jspdf'

// ─── Layout constants (letter, portrait, inches → mm) ───────────────────────
const PW = 215.9   // 8.5in
const PH = 279.4   // 11in
const ML = 14      // left margin
const MR = 14      // right margin
const CW = PW - ML - MR  // content width = 187.9mm
const FS_LABEL = 7.5
const FS_VALUE = 9
const FS_SMALL = 6.5
const ROW_H = 7    // standard field row height
const SECTION_H = 6.5

// ─── Helpers ────────────────────────────────────────────────────────────────

function newDoc() {
  return new jsPDF({ unit: 'mm', format: 'letter', orientation: 'portrait' })
}

// Draw a filled black section header band (like the official form)
function sectionHeader(pdf, y, text) {
  pdf.setFillColor(0, 0, 0)
  pdf.rect(ML, y, CW, SECTION_H, 'F')
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(8)
  pdf.setTextColor(255, 255, 255)
  pdf.text(text, ML + 2, y + 4.5)
  pdf.setTextColor(0, 0, 0)
  return y + SECTION_H
}

// Draw a field with label on top, underline below, value filled in
function field(pdf, x, y, w, label, value, opts = {}) {
  // Label
  pdf.setFont('helvetica', opts.boldLabel ? 'bold' : 'normal')
  pdf.setFontSize(FS_LABEL)
  pdf.setTextColor(30, 30, 30)
  pdf.text(label, x, y + 3)
  // Underline
  pdf.setDrawColor(150, 150, 150)
  pdf.line(x, y + ROW_H, x + w, y + ROW_H)
  // Value
  if (value) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_VALUE)
    pdf.setTextColor(0, 0, 0)
    const lines = pdf.splitTextToSize(String(value), w - 1)
    pdf.text(lines[0], x + 0.5, y + ROW_H - 1.5)
  }
}

// Inline label: value on same row (no underline, for compact rows)
function inlineField(pdf, x, y, w, label, value) {
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(FS_LABEL)
  pdf.setTextColor(30, 30, 30)
  pdf.text(label, x, y)
  pdf.setDrawColor(150, 150, 150)
  pdf.line(x, y + 3.5, x + w, y + 3.5)
  if (value) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_VALUE)
    const lines = pdf.splitTextToSize(String(value), w - 1)
    pdf.text(lines[0], x + 0.5, y + 3)
  }
}

// Draw a checkbox (square) with optional check mark
function checkbox(pdf, x, y, checked) {
  const sz = 3.2
  pdf.setDrawColor(80, 80, 80)
  pdf.setLineWidth(0.3)
  pdf.rect(x, y - sz + 0.5, sz, sz)
  if (checked) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    pdf.setTextColor(0, 0, 0)
    pdf.text('X', x + 0.5, y - 0.2)
  }
  pdf.setLineWidth(0.2)
}

// Yes/No checkbox pair — returns x position after the pair
function yesNo(pdf, x, y, checked) {
  // Yes
  checkbox(pdf, x, y, checked === true)
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(FS_LABEL)
  pdf.setTextColor(30, 30, 30)
  pdf.text('Yes', x + 4, y)
  // No
  checkbox(pdf, x + 12, y, checked === false)
  pdf.text('No', x + 16, y)
  return x + 24
}

// Cost row with Yes/No checkboxes on left (for trade permits)
function costRow(pdf, y, label, value, hasCheckbox, isChecked) {
  if (hasCheckbox) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(FS_LABEL)
    pdf.setTextColor(30, 30, 30)
    pdf.text(label, ML, y)
    yesNo(pdf, ML + 38, y, isChecked)
  } else {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(FS_LABEL)
    pdf.setTextColor(30, 30, 30)
    pdf.text(label, ML, y)
  }
  // Dollar amount right-aligned
  const amt = value || '$________________'
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(FS_VALUE)
  pdf.setDrawColor(150, 150, 150)
  pdf.line(ML + CW - 40, y + 0.5, ML + CW, y + 0.5)
  if (value) pdf.text(value, ML + CW - 1, y, { align: 'right' })
  return y + ROW_H
}

// Full-width bordered box for disclaimer text
function disclaimerBox(pdf, y, text, italic = false) {
  pdf.setDrawColor(100, 100, 100)
  pdf.setLineWidth(0.3)
  const lines = pdf.splitTextToSize(text, CW - 4)
  const boxH = lines.length * 3.8 + 4
  pdf.rect(ML, y, CW, boxH)
  pdf.setFont('helvetica', italic ? 'italic' : 'normal')
  pdf.setFontSize(FS_SMALL)
  pdf.setTextColor(30, 30, 30)
  pdf.text(lines, ML + 2, y + 4)
  return y + boxH
}

// Page footer
function pageFooter(pdf, docRef) {
  const pages = pdf.internal.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    pdf.setPage(i)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(6)
    pdf.setTextColor(120, 120, 120)
    pdf.text(docRef, PW - MR, PH - 5, { align: 'right' })
    pdf.text(`Generated by Parcoria · parcoria.com · Page ${i} of ${pages}`, ML, PH - 5)
  }
}

// ─── Building Permit (Doc.983) ───────────────────────────────────────────────

function buildBuildingPDF(form, totalCost) {
  const pdf = newDoc()
  let y = ML

  // ── Official header ──────────────────────────────────────────────────────
  // Top instruction box
  pdf.setDrawColor(200, 150, 0)
  pdf.setFillColor(255, 248, 220)
  pdf.rect(ML, y, CW, 8, 'FD')
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(8)
  pdf.setTextColor(180, 100, 0)
  pdf.text('Download and open PDF file before entering information', PW / 2, y + 3.5, { align: 'center' })
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(6.5)
  pdf.setTextColor(80, 80, 80)
  pdf.text('Must be submitted to https://www.durhamnc.gov/467/Dplans', PW / 2, y + 6.5, { align: 'center' })
  y += 12

  // Title block
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(14)
  pdf.setTextColor(0, 0, 0)
  pdf.text('BUILDING PERMIT APPLICATION', PW / 2, y + 5, { align: 'center' })
  y += 9
  pdf.setFontSize(9)
  pdf.text('CITY-COUNTY BUILDING & SAFETY DEPARTMENT', PW / 2, y + 4, { align: 'center' })
  y += 6
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.text('101 City Hall Plaza, Ground Floor, Suite 400, Durham NC 27701', PW / 2, y + 4, { align: 'center' })
  y += 5
  pdf.text('Phone: (919) 560-4144', PW / 2, y + 4, { align: 'center' })
  y += 8

  // Intro box
  const introText = 'This form is to be submitted with all non-residential structures and new residential primary structure construction projects, along with either a Non-Residential or Residential checklist as applicable.'
  y = disclaimerBox(pdf, y, introText) + 3

  // ── PROJECT INFORMATION ──────────────────────────────────────────────────
  y = sectionHeader(pdf, y, 'PROJECT INFORMATION')
  y += 1

  // Job Address | Lot/Unit
  field(pdf, ML, y, CW - 35, 'JOB ADDRESS:', form.jobAddress)
  field(pdf, ML + CW - 33, y, 33, 'LOT/UNIT:', form.lotUnit)
  y += ROW_H + 2

  // Site Plan | Subdivision
  field(pdf, ML, y, 70, 'SITE PLAN NUMBER* (for all nonresidential jobs):', '')
  field(pdf, ML + 75, y, CW - 75, 'SUBDIVISION:', form.subdivision)
  y += ROW_H + 2

  // Job Description
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(FS_LABEL)
  pdf.setTextColor(30, 30, 30)
  pdf.text('JOB DESCRIPTION (Must align with the checklist, construction plan, and site plan where required):', ML, y + 3)
  y += 5
  pdf.setDrawColor(150, 150, 150)
  pdf.line(ML, y + 2, ML + CW, y + 2)
  if (form.jobDescription) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_VALUE)
    const lines = pdf.splitTextToSize(form.jobDescription, CW - 2)
    pdf.text(lines[0], ML + 0.5, y + 1.5)
  }
  y += 6

  // ── CONTRACTOR INFORMATION ───────────────────────────────────────────────
  y = sectionHeader(pdf, y, 'CONTRACTOR INFORMATION')
  y += 1

  // Contractor | License
  field(pdf, ML, y, CW - 60, 'CONTRACTOR:', form.contractorName)
  field(pdf, ML + CW - 58, y, 58, 'STATE CONTRACTOR LICENSE NO.:', form.contractorLicense)
  y += ROW_H + 2

  // Email | Phone
  field(pdf, ML, y, CW - 60, 'EMAIL FOR POINT-OF-CONTACT:', form.contractorEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.contractorPhone)
  y += ROW_H + 2

  // CID — with asterisk note
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(FS_LABEL)
  pdf.setTextColor(30, 30, 30)
  pdf.text('REQUIRED DURHAM CONTRACTOR ID (CID)*:', ML, y + 3)
  pdf.setDrawColor(150, 150, 150)
  pdf.line(ML + 70, y + 4, ML + 70 + 50, y + 4)
  if (form.durhamCID) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_VALUE)
    pdf.text(String(form.durhamCID), ML + 71, y + 3.5)
  }
  y += 5
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(6)
  pdf.setTextColor(80, 80, 80)
  pdf.text('* To request a CID, email your contact information, including any construction licenses held, to permittechnicians@durhamnc.gov.', ML, y + 3)
  y += 5

  // Address | City | State | ZIP
  field(pdf, ML, y, CW - 80, 'ADDRESS:', form.contractorAddress)
  field(pdf, ML + CW - 78, y, 35, 'CITY:', form.contractorCity)
  field(pdf, ML + CW - 41, y, 15, 'STATE:', form.contractorState || 'NC')
  field(pdf, ML + CW - 24, y, 24, 'ZIP CODE:', form.contractorZip)
  y += ROW_H + 3

  // Architect row
  field(pdf, ML, y, CW - 80, 'ARCHITECT:', form.architectName)
  field(pdf, ML + CW - 78, y, 45, 'EMAIL:', form.architectEmail)
  field(pdf, ML + CW - 31, y, 31, 'PHONE:', form.architectPhone)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 80, 'ADDRESS:', '')
  field(pdf, ML + CW - 78, y, 35, 'CITY:', '')
  field(pdf, ML + CW - 41, y, 15, 'STATE:', '')
  field(pdf, ML + CW - 24, y, 24, 'ZIP CODE:', '')
  y += ROW_H + 3

  // ── PROPERTY OWNER INFORMATION ───────────────────────────────────────────
  y = sectionHeader(pdf, y, 'PROPERTY OWNER INFORMATION')
  y += 1

  field(pdf, ML, y, CW, 'PROPERTY OWNER NAME:', form.ownerName)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.ownerEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.ownerPhone)
  y += ROW_H + 3

  // ── CONSTRUCTION COSTS ───────────────────────────────────────────────────
  y = sectionHeader(pdf, y, 'CONSTRUCTION COSTS  Must reflect current market value for labor and materials (Materials obtained for free must be accounted for in the project costs)')
  y += 2

  y = costRow(pdf, y, 'BUILDING WORK:', form.building, false, null)
  y += 1
  y = costRow(pdf, y, 'ELECTRICAL WORK?', form.electrical, true, form.hasElectrical)
  y += 1
  y = costRow(pdf, y, 'PLUMBING WORK?', form.plumbing, true, form.hasPlumbing)
  y += 1
  y = costRow(pdf, y, 'MECHANICAL WORK?', form.mechanical, true, form.hasMechanical)
  y += 1
  y = costRow(pdf, y, 'FIRE PROTECTION WORK?', form.fire, true, form.hasFire)
  y += 3

  // Total
  pdf.setDrawColor(0, 0, 0)
  pdf.setLineWidth(0.5)
  pdf.line(ML + CW - 60, y, ML + CW, y)
  pdf.setLineWidth(0.2)
  y += 1
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(9)
  pdf.setTextColor(0, 0, 0)
  pdf.text('TOTAL PROJECT COST', ML + CW - 62, y + 4, { align: 'right' })
  pdf.text(
    '$' + (totalCost || 0).toLocaleString('en-US', { minimumFractionDigits: 2 }),
    ML + CW,
    y + 4,
    { align: 'right' }
  )
  y += 8

  // ── REQUIRED QUESTIONS ───────────────────────────────────────────────────
  const questions = [
    { text: 'Does this project exceed 12k sq. ft of land disturbance?', val: form.landDisturbance },
    { text: 'Does this project include public food service area(s)?', val: form.publicFood },
    { text: 'Is this a single-family, duplex, or townhome that includes a sprinkler? (If "Yes" check "Yes" for Plumbing above)', val: form.sprinkler },
    { text: 'Will a sub-slab soil exhaust system be installed?', val: form.subSlab },
    { text: 'Is this property currently serviced or planned to be serviced by a well or septic tank?  *', val: form.wellSeptic },
    { text: 'Is an alteration to an existing natural or man-made drainage system proposed as part of this work?  **', val: form.drainage },
  ]

  questions.forEach(q => {
    const qLines = pdf.splitTextToSize(q.text, CW - 28)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_LABEL)
    pdf.setTextColor(30, 30, 30)
    pdf.text(qLines, ML, y + 3)
    yesNo(pdf, ML + CW - 24, y + 3, q.val)
    y += Math.max(qLines.length * 4, ROW_H) + 1
  })

  // Footnotes
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(FS_SMALL)
  pdf.setTextColor(60, 60, 60)
  pdf.text('*If "Yes," contact Environmental Health at 919-560-7800 for their approval.', ML, y + 3)
  y += 4.5
  pdf.text('**If "Yes," a separate drainage permit application may be required. Contact 919-560-4326 for more information.', ML, y + 3)
  y += 7

  // ── AUTHORIZATION ────────────────────────────────────────────────────────
  y = sectionHeader(pdf, y, 'AUTHORIZATION FROM OWNER OR AUTHORIZED AGENT')
  y += 2

  const auth = 'The owner or authorized agent of the owner who signs this application is responsible for determining whether sewer, water, gas and other utilities are available for this site. Also, all easements and restrictions must be shown on the plot plan. Where applicable, allowable impervious coverage must be verified by a certified survey at the completion of all site work. The applicant must adhere to all codes and ordinances. A separate permit is required for each trade that work is to be performed. No trade permits will be issued until the accompanying building permit is issued. Applications which are not completed to "ISSUED" status within 6 months will expire. By signing this application, the applicant assumes all responsibility for these items.'
  y = disclaimerBox(pdf, y, auth, true) + 4

  // Signature line
  field(pdf, ML, y, 65, 'PRINT NAME:', form.signerName)
  field(pdf, ML + 68, y, 80, 'SIGNATURE:', '')
  field(pdf, ML + 152, y, CW - 152, 'DATE:', form.signDate)

  pageFooter(pdf, 'Doc.983 Rev.08.01.2025')
  return pdf
}

// ─── Electrical Permit ───────────────────────────────────────────────────────

function buildElectricalPDF(form) {
  const pdf = newDoc()
  let y = ML

  // Header
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(0, 0, 0)
  pdf.text('ELECTRICAL PERMIT APPLICATION', PW / 2, y + 6, { align: 'center' })
  y += 9
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.text('City-County Building & Safety Department · 101 City Hall Plaza, Suite 400, Durham NC 27701 · (919) 560-4144', PW / 2, y + 4, { align: 'center' })
  y += 7
  pdf.setFontSize(7)
  pdf.setTextColor(80, 80, 80)
  pdf.text('Submit via LDO Portal: ldo4.durhamnc.gov/DurhamWeb', PW / 2, y + 3, { align: 'center' })
  y += 8

  y = sectionHeader(pdf, y, 'PROJECT INFORMATION')
  y += 1
  field(pdf, ML, y, CW, 'JOB ADDRESS:', form.jobAddress)
  y += ROW_H + 2
  field(pdf, ML, y, CW, 'DESCRIPTION OF WORK:', form.jobDescription)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'SCOPE OF ELECTRICAL WORK')
  y += 2
  if (form.workScope?.length > 0) {
    form.workScope.forEach(item => {
      checkbox(pdf, ML, y + 0.5, true)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(FS_LABEL)
      pdf.setTextColor(30, 30, 30)
      pdf.text(item, ML + 5, y + 3)
      y += 5.5
    })
  } else {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_LABEL)
    pdf.setTextColor(120, 120, 120)
    pdf.text('(No scope items selected)', ML + 2, y + 3)
    y += 6
  }
  y += 2

  y = sectionHeader(pdf, y, 'ELECTRICAL DETAILS')
  y += 1
  field(pdf, ML, y, 60, 'SERVICE SIZE (AMPS):', form.serviceAmps)
  field(pdf, ML + 64, y, 60, 'NUMBER OF CIRCUITS:', form.numCircuits)
  field(pdf, ML + 128, y, CW - 128, 'ESTIMATED COST:', form.estimatedCost || '$0.00')
  y += ROW_H + 2
  field(pdf, ML, y, CW, 'WIRING METHOD:', form.wiringMethod)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'CONTRACTOR INFORMATION')
  y += 1
  field(pdf, ML, y, CW - 60, 'CONTRACTOR:', form.contractorName)
  field(pdf, ML + CW - 58, y, 58, 'NC ELECTRICAL LICENSE NO.:', form.contractorLicense)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.contractorEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.contractorPhone)
  y += ROW_H + 2
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(FS_LABEL)
  pdf.text('REQUIRED DURHAM CONTRACTOR ID (CID)*:', ML, y + 3)
  pdf.setDrawColor(150, 150, 150)
  pdf.line(ML + 70, y + 4, ML + 70 + 50, y + 4)
  if (form.durhamCID) {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(FS_VALUE)
    pdf.text(String(form.durhamCID), ML + 71, y + 3.5)
  }
  y += 5
  field(pdf, ML, y, CW - 80, 'ADDRESS:', form.contractorAddress)
  field(pdf, ML + CW - 78, y, 35, 'CITY:', form.contractorCity)
  field(pdf, ML + CW - 41, y, 15, 'STATE:', form.contractorState || 'NC')
  field(pdf, ML + CW - 24, y, 24, 'ZIP CODE:', form.contractorZip)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'PROPERTY OWNER INFORMATION')
  y += 1
  field(pdf, ML, y, CW, 'PROPERTY OWNER NAME:', form.ownerName)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.ownerEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.ownerPhone)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'AUTHORIZATION')
  y += 2
  y = disclaimerBox(pdf, y, 'By submitting this application, the applicant certifies that all electrical work will be performed by or under the supervision of a NC-licensed electrical contractor, and that all work will conform to the 2023 NEC as adopted by NC and all applicable Durham codes.', true) + 4

  field(pdf, ML, y, 65, 'PRINT NAME:', form.signerName)
  field(pdf, ML + 68, y, 80, 'SIGNATURE:', '')
  field(pdf, ML + 152, y, CW - 152, 'DATE:', form.signDate)

  pageFooter(pdf, 'Durham LDO Portal — Electrical Permit')
  return pdf
}

// ─── Plumbing Permit ─────────────────────────────────────────────────────────

function buildPlumbingPDF(form) {
  const pdf = newDoc()
  let y = ML

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(0, 0, 0)
  pdf.text('PLUMBING PERMIT APPLICATION', PW / 2, y + 6, { align: 'center' })
  y += 9
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.text('City-County Building & Safety Department · 101 City Hall Plaza, Suite 400, Durham NC 27701 · (919) 560-4144', PW / 2, y + 4, { align: 'center' })
  y += 7
  pdf.setFontSize(7)
  pdf.setTextColor(80, 80, 80)
  pdf.text('Submit via LDO Portal: ldo4.durhamnc.gov/DurhamWeb', PW / 2, y + 3, { align: 'center' })
  y += 8

  y = sectionHeader(pdf, y, 'PROJECT INFORMATION')
  y += 1
  field(pdf, ML, y, CW, 'JOB ADDRESS:', form.jobAddress)
  y += ROW_H + 2
  field(pdf, ML, y, CW, 'DESCRIPTION OF WORK:', form.jobDescription)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'SCOPE OF PLUMBING WORK')
  y += 2
  if (form.workScope?.length > 0) {
    form.workScope.forEach(item => {
      checkbox(pdf, ML, y + 0.5, true)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(FS_LABEL)
      pdf.setTextColor(30, 30, 30)
      pdf.text(item, ML + 5, y + 3)
      y += 5.5
    })
  } else {
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(FS_LABEL); pdf.setTextColor(120, 120, 120)
    pdf.text('(No scope items selected)', ML + 2, y + 3); y += 6
  }
  y += 2

  y = sectionHeader(pdf, y, 'PLUMBING DETAILS')
  y += 1
  field(pdf, ML, y, 90, 'NUMBER OF FIXTURES:', form.numCircuits)
  field(pdf, ML + 94, y, CW - 94, 'ESTIMATED COST:', form.estimatedCost || '$0.00')
  y += ROW_H + 2
  pdf.setFont('helvetica', 'bold'); pdf.setFontSize(FS_LABEL); pdf.setTextColor(30,30,30)
  pdf.text('DOES SCOPE INCLUDE GAS PIPING?', ML, y + 3)
  yesNo(pdf, ML + 62, y + 3, form.gasWork)
  if (form.gasWork && form.gasType) {
    field(pdf, ML + 90, y, CW - 90, 'GAS TYPE:', form.gasType)
  }
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'CONTRACTOR INFORMATION')
  y += 1
  field(pdf, ML, y, CW - 60, 'CONTRACTOR:', form.contractorName)
  field(pdf, ML + CW - 58, y, 58, 'NC PLUMBING LICENSE NO.:', form.contractorLicense)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.contractorEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.contractorPhone)
  y += ROW_H + 2
  pdf.setFont('helvetica', 'bold'); pdf.setFontSize(FS_LABEL); pdf.text('REQUIRED DURHAM CONTRACTOR ID (CID)*:', ML, y + 3)
  pdf.setDrawColor(150, 150, 150); pdf.line(ML + 70, y + 4, ML + 120, y + 4)
  if (form.durhamCID) { pdf.setFont('helvetica', 'normal'); pdf.setFontSize(FS_VALUE); pdf.text(String(form.durhamCID), ML + 71, y + 3.5) }
  y += 5
  field(pdf, ML, y, CW - 80, 'ADDRESS:', form.contractorAddress)
  field(pdf, ML + CW - 78, y, 35, 'CITY:', form.contractorCity)
  field(pdf, ML + CW - 41, y, 15, 'STATE:', form.contractorState || 'NC')
  field(pdf, ML + CW - 24, y, 24, 'ZIP CODE:', form.contractorZip)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'PROPERTY OWNER INFORMATION')
  y += 1
  field(pdf, ML, y, CW, 'PROPERTY OWNER NAME:', form.ownerName)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.ownerEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.ownerPhone)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'AUTHORIZATION')
  y += 2
  y = disclaimerBox(pdf, y, 'By submitting this application, the applicant certifies that all plumbing work will be performed by or under the supervision of a NC-licensed plumbing contractor, and that all work will conform to the 2018 NC Plumbing Code and applicable Durham amendments.', true) + 4
  field(pdf, ML, y, 65, 'PRINT NAME:', form.signerName)
  field(pdf, ML + 68, y, 80, 'SIGNATURE:', '')
  field(pdf, ML + 152, y, CW - 152, 'DATE:', form.signDate)

  pageFooter(pdf, 'Durham LDO Portal — Plumbing Permit')
  return pdf
}

// ─── Mechanical Permit ───────────────────────────────────────────────────────

function buildMechanicalPDF(form) {
  const pdf = newDoc()
  let y = ML

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(0, 0, 0)
  pdf.text('MECHANICAL / HVAC PERMIT APPLICATION', PW / 2, y + 6, { align: 'center' })
  y += 9
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.text('City-County Building & Safety Department · 101 City Hall Plaza, Suite 400, Durham NC 27701 · (919) 560-4144', PW / 2, y + 4, { align: 'center' })
  y += 7
  pdf.setFontSize(7)
  pdf.setTextColor(80, 80, 80)
  pdf.text('Submit via LDO Portal: ldo4.durhamnc.gov/DurhamWeb', PW / 2, y + 3, { align: 'center' })
  y += 8

  y = sectionHeader(pdf, y, 'PROJECT INFORMATION')
  y += 1
  field(pdf, ML, y, CW, 'JOB ADDRESS:', form.jobAddress)
  y += ROW_H + 2
  field(pdf, ML, y, CW, 'DESCRIPTION OF WORK:', form.jobDescription)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'SCOPE OF MECHANICAL WORK')
  y += 2
  if (form.workScope?.length > 0) {
    form.workScope.forEach(item => {
      checkbox(pdf, ML, y + 0.5, true)
      pdf.setFont('helvetica', 'normal'); pdf.setFontSize(FS_LABEL); pdf.setTextColor(30,30,30)
      pdf.text(item, ML + 5, y + 3); y += 5.5
    })
  } else {
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(FS_LABEL); pdf.setTextColor(120, 120, 120)
    pdf.text('(No scope items selected)', ML + 2, y + 3); y += 6
  }
  y += 2

  y = sectionHeader(pdf, y, 'MECHANICAL DETAILS')
  y += 1
  field(pdf, ML, y, 90, 'SYSTEM TYPE:', form.wiringMethod)
  field(pdf, ML + 94, y, CW - 94, 'ESTIMATED COST:', form.estimatedCost || '$0.00')
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'CONTRACTOR INFORMATION')
  y += 1
  field(pdf, ML, y, CW - 60, 'CONTRACTOR:', form.contractorName)
  field(pdf, ML + CW - 58, y, 58, 'NC HVAC LICENSE NO.:', form.contractorLicense)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.contractorEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.contractorPhone)
  y += ROW_H + 2
  pdf.setFont('helvetica', 'bold'); pdf.setFontSize(FS_LABEL); pdf.text('REQUIRED DURHAM CONTRACTOR ID (CID)*:', ML, y + 3)
  pdf.setDrawColor(150, 150, 150); pdf.line(ML + 70, y + 4, ML + 120, y + 4)
  if (form.durhamCID) { pdf.setFont('helvetica', 'normal'); pdf.setFontSize(FS_VALUE); pdf.text(String(form.durhamCID), ML + 71, y + 3.5) }
  y += 5
  field(pdf, ML, y, CW - 80, 'ADDRESS:', form.contractorAddress)
  field(pdf, ML + CW - 78, y, 35, 'CITY:', form.contractorCity)
  field(pdf, ML + CW - 41, y, 15, 'STATE:', form.contractorState || 'NC')
  field(pdf, ML + CW - 24, y, 24, 'ZIP CODE:', form.contractorZip)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'PROPERTY OWNER INFORMATION')
  y += 1
  field(pdf, ML, y, CW, 'PROPERTY OWNER NAME:', form.ownerName)
  y += ROW_H + 2
  field(pdf, ML, y, CW - 60, 'EMAIL:', form.ownerEmail)
  field(pdf, ML + CW - 58, y, 58, 'PHONE:', form.ownerPhone)
  y += ROW_H + 4

  y = sectionHeader(pdf, y, 'AUTHORIZATION')
  y += 2
  y = disclaimerBox(pdf, y, 'By submitting this application, the applicant certifies that all mechanical work will be performed by or under the supervision of a NC-licensed HVAC/mechanical contractor, and that all work will conform to the 2018 NC Mechanical Code and applicable Durham amendments.', true) + 4
  field(pdf, ML, y, 65, 'PRINT NAME:', form.signerName)
  field(pdf, ML + 68, y, 80, 'SIGNATURE:', '')
  field(pdf, ML + 152, y, CW - 152, 'DATE:', form.signDate)

  pageFooter(pdf, 'Durham LDO Portal — Mechanical Permit')
  return pdf
}

// ─── Public API ──────────────────────────────────────────────────────────────

export function generatePermitPDF(permitType, form, totalCost) {
  switch (permitType) {
    case 'electrical':  return buildElectricalPDF(form)
    case 'plumbing':    return buildPlumbingPDF(form)
    case 'mechanical':  return buildMechanicalPDF(form)
    default:            return buildBuildingPDF(form, totalCost)
  }
}

export function downloadPermitPDF(permitType, form, totalCost) {
  const pdf = generatePermitPDF(permitType, form, totalCost)
  const address = (form.jobAddress || 'durham-permit').replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 30)
  const filename = `durham-${permitType}-permit-${address}.pdf`
  pdf.save(filename)
  return filename
}
